name: Blog

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v14
        with:
          name: gvolpe-blog
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix develop -c bundle exec jekyll build
